### ISSUE TITLE
Embedded Toolkit

### ISSUE THREAD

**Issue by matthijsroobeek** [supercamel/ninjaskit#1]
Hi Camel,

Your projects look very interesting and useful, especially the ETK, but it seems offline.
Could you upload it, I'd like to take a look at it!

Cheers!

**Comment by supercamel** [comment]
Whoops! Sorry! I removed ETK recently due to a misunderstanding over licensing. ETK & Ninjaskit are GPLed code, but they need to be changed to the MIT license. I'll start a new repo for ETK once that is done. I'll do it now. Gime an hour :-)

**Comment by matthijsroobeek** [comment]
Wow, thanks!

**Comment by supercamel** [comment]
No probs, it's back up now.
